#项目服务器配置

spring:
    datasource:
        druid:
            url: jdbc:mysql://localhost:3306/line?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username:
            password:
    redis:
        host: redis
        password:
        jedis:
          pool:
            min-idle: 0
            max-idle: 20
#            max-wait: 5000
            max-active: 100
        port: 6379
